apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    {{- include "labels" . | nindent 4 }}
  type: loadbalancer
  ports:
    - protocol: TCP
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.container.port }}
